services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "10000:10000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./website
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      