services:
  - type: web
    name: athena-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.backend
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 10000

      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        sync: false

      - key: ALGORITHM
        sync: false
        
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
        
      - key: REDIS_HOST
        sync: false
        
      - key: REDIS_PORT
        sync: false
        
      - key: REDIS_PASSWORD
        sync: false
        
      - key: REDIS_DB
        sync: false
        
      - key: ATHENA_EMAIL
        sync: false

      - key: ATHENA_PASSWORD
        sync: false
      
      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: athena-frontend
    runtime: docker
    dockerfilePath: ./website/Dockerfile.frontend
    dockerContext: ./website
    envVars:
      - key: ATHENA_API_BASE
        value: https://athena-backend.onrender.com